### PR TITLE
Upgrade jQuery to version 3

### PR DESCRIPTION
**Pull request by eatyourgreens**
Remove jquerify.
Add jquery 3 to index.html.
Set $ to window.jQuery wherever it's used.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Hopefully it works. I couldn't figure out how to properly test it without deploying to a live site.

**Comment by astopy** [comment]
`npm run start` should start a local server, assuming it's still possible to install the required Node modules.

**Comment by astopy** [comment]
D'oh, this was all going too smoothly. There's an error when viewing individual subject pages:

https://talk.cyclonecenter.org/#/groups/GCC00001rj

```
[Error] TypeError: t.children().emoticonize is not a function. (In 't.children().emoticonize()', 't.children().emoticonize' is undefined)
	convert (application-2018-01-23_12-34-55.js:1:364759)
	(anonymous function) (application-2018-01-23_12-34-55.js:1:436982)
	(anonymous function) (application-2018-01-23_12-34-55.js:1:437360)
	exports (application-2018-01-23_12-34-55.js:1:437372)
	(anonymous function) (application-2018-01-23_12-34-55.js:1:439117)
	(anonymous function) (application-2018-01-23_12-34-55.js:1:439415)
	exports (application-2018-01-23_12-34-55.js:1:439427)
	(anonymous function) (application-2018-01-23_12-34-55.js:1:451895)
	(anonymous function) (application-2018-01-23_12-34-55.js:1:452418)
	exports (application-2018-01-23_12-34-55.js:1:452430)
	render (application-2018-01-23_12-34-55.js:1:219729)
	render (application-2018-01-23_12-34-55.js:1:210048)
	(anonymous function) (application-2018-01-23_12-34-55.js:1:210264)
	(anonymous function) (application-2018-01-23_12-34-55.js:1:380041)
	p (application-2018-01-23_12-34-55.js:1:51440)
	fireWith (application-2018-01-23_12-34-55.js:1:52212)
	fire (application-2018-01-23_12-34-55.js:1:52258)
	tapped (application-2018-01-23_12-34-55.js:1:132945)
	(anonymous function) (application-2018-01-23_12-34-55.js:1:131831)
	succeed (application-2018-01-23_12-34-55.js:1:132604)
	(anonymous function) (application-2018-01-23_12-34-55.js:1:131831)
	respond (application-2018-01-23_12-34-55.js:1:36427)
	dispatch (application-2018-01-23_12-34-55.js:1:73362)
	a (application-2018-01-23_12-34-55.js:1:69333)
	trigger (application-2018-01-23_12-34-55.js:1:72043)
	(anonymous function) (application-2018-01-23_12-34-55.js:1:79524)
	each (application-2018-01-23_12-34-55.js:1:48593)
	each (application-2018-01-23_12-34-55.js:1:45136)
	trigger (application-2018-01-23_12-34-55.js:1:79497)
	receive (application-2018-01-23_12-34-55.js:1:131675)
	(anonymous function) (application-2018-01-23_12-34-55.js:1:130420)
	dispatch (application-2018-01-23_12-34-55.js:1:73362)
	a (application-2018-01-23_12-34-55.js:1:69333)
```

**Comment by astopy** [comment]
I'm redeploying from master now.

**Comment by eatyourgreens** [comment]
Looks like that function is called from the markdown renderer. Must be a jquery plugin for emoticons, or something.

https://github.com/zooniverse/Talk/blob/4b974b6944386b37c91046d3c67206519515d76d/app/lib/markdown.coffee#L30

**Comment by eatyourgreens** [comment]
Looking through `/app/lib`, there's a few jquery plugins that might not work with the latest version.

**Comment by eatyourgreens** [comment]
`npm run start` starts a local server on port 9294, but `http://localhost:9294` just gives me `Not Found: /`.

**Comment by eatyourgreens** [comment]
I'm not sure, but I think the problem here is that the plugins run before `jQuery` is defined.

**Comment by eatyourgreens** [comment]
@astopy I've tried replacing `jquerify` with the `jquery` package instead. Does that fix the plugin error?

**Comment by astopy** [comment]
Hmm, now it doesn't even render the page. I get this in the terminal:

```
> talk@0.0.1 start /Users/adam/Code/Talk
> hem server

path.existsSync is now called `fs.existsSync`.
>> Strata web server version 0.15.1 running on node 0.10.48
>> Listening on 0.0.0.0:9294, CTRL+C to stop
path.exists is now called `fs.exists`.
util.pump() is deprecated. Use readableStream.pipe() instead.
Unhandled error!
Error: undefined
```

And also this in the JS console:

```
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (application.js, line 0)
[Error] ReferenceError: Can't find variable: require
	Global Code (localhost:20)
```

**Comment by astopy** [comment]
@eatyourgreens By the way, that not found error might be because you need to configure it for a specific project before starting it, e.g. `./configure.rb asteroid && npm run start`

**Comment by eatyourgreens** [comment]
That's very odd. `npm start` runs without error here (node 0.10.48.)

`configure.rb` gives me a ruby error when I try to run it. 
```shell
/Users/odonnell/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- active_support/core_ext/hash (LoadError)
	from /Users/odonnell/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./configure.rb:3:in `<main>'
```

**Comment by astopy** [comment]
npm start doesn't encounter the error until I actually load the page.

I'm running it in ruby 2.1.2, but you may also need to run bundle install I think.

**Comment by eatyourgreens** [comment]
I knew I was missing a step. `bundle install` fails with Ruby 2.3. I'm trying 1.9 now. I have the site running locally but I get `Uncaught module jquery not found` in the console. 😞

**Comment by eatyourgreens** [comment]
Same `Uncaught module jquery not found` here with Ruby 2.1.2, but I do see the Talk footer in the browser!

**Comment by eatyourgreens** [comment]
Updated to remove `jqueryify` from the zooniverse library, and from project components. This should work now @astopy. It runs locally for me, and `$().jquery` reports 3.2.1 in the console.

To test the emoticon plugin, try viewing subject AGZ0005efq on galaxy_zoo staging.

**Comment by eatyourgreens** [comment]
TODO: maybe figure out why this needs an outdated fork of zooniverse.js. Updating the zooniverse dependency breaks the build of `application.js` for me.

**Pull request merged**
